version: 2
project_name: go-novel-dl
env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - go run ./tools/iconprep
    - go install github.com/tc-hib/go-winres@latest
    - go-winres make --in ./winres/winres.json --out ./cmd/novel-dl/rsrc

builds:
  - id: unix
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: ./cmd/novel-dl
    binary: novel-dl
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
  - id: win
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: ./cmd/novel-dl
    binary: novel-dl
    goos:
      - windows
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w

checksum:
  name_template: "go-novel-dl_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - fix typo
      - Merge pull request
      - Merge branch
      - Merge remote-tracking
      - go mod tidy

archives:
  - id: unix
    ids:
      - unix
    name_template: "go-novel-dl_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats:
      - tar.gz
  - id: win
    ids:
      - win
    name_template: "go-novel-dl_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats:
      - zip

nfpms:
  - license: AGPL 3.0
    homepage: https://github.com/guohuiyuan/go-novel-dl
    maintainer: guohuiyuan
    file_name_template: "go-novel-dl_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats:
      - deb
      - rpm
