package cli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/guohuiyuan/go-novel-dl/internal/app"
)

func newCleanCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "clean",
		Short: "Clear application logs, caches, and book data",
	}
	cmd.AddCommand(newCleanStateCmd(), newCleanLogsCmd(), newCleanCacheCmd(), newCleanBookCmd())
	return cmd
}

func newCleanStateCmd() *cobra.Command {
	var yes bool
	cmd := &cobra.Command{
		Use:   "state",
		Short: "Clean internal state (runtime state, temp info)",
		RunE: func(cmd *cobra.Command, args []string) error {
			console := newConsole()
			runtime := app.NewRuntime(configPtr(), console)

			path := runtime.State.Path()
			if _, err := os.Stat(path); err != nil {
				if errors.Is(err, os.ErrNotExist) {
					console.Infof("No internal state found. Nothing to clean.")
					return nil
				}
				return err
			}
			console.Infof("Internal state file: %s", path)
			if !yes {
				confirm, err := console.Confirm("Are you sure you want to remove internal state?", false)
				if err != nil {
					return err
				}
				if !confirm {
					console.Warnf("Cancelled.")
					return nil
				}
			}
			if err := os.Remove(path); err != nil {
				return err
			}
			_ = os.Remove(filepath.Dir(path))
			console.Successf("Internal state removed successfully.")
			return nil
		},
	}
	cmd.Flags().BoolVarP(&yes, "yes", "y", false, "Skip confirmation prompt")
	return cmd
}

func newCleanLogsCmd() *cobra.Command {
	var configPath string
	var yes bool
	var dryRun bool
	cmd := &cobra.Command{
		Use:   "logs",
		Short: "Clean log files generated by the application",
		RunE: func(cmd *cobra.Command, args []string) error {
			console := newConsole()
			runtime, _, err := loadRuntime(console, configPath)
			if err != nil {
				return err
			}
			if runtime == nil {
				return nil
			}

			removed, err := runtime.CleanLogs(true)
			if err != nil {
				return err
			}
			if len(removed) == 0 {
				console.Infof("No log files to clean")
				return nil
			}

			console.Infof("Found %d log files to clean.", len(removed))
			if dryRun {
				for _, path := range removed {
					console.Infof("Would remove %s", path)
				}
				return nil
			}
			if !yes {
				confirm, err := console.Confirm("Are you sure you want to remove these log files?", false)
				if err != nil {
					return err
				}
				if !confirm {
					console.Warnf("Cancelled.")
					return nil
				}
			}
			removed, err = runtime.CleanLogs(false)
			if err != nil {
				return err
			}
			for _, path := range removed {
				console.Successf("Removed %s", path)
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&configPath, "config", "", "Path to the configuration file")
	cmd.Flags().BoolVarP(&yes, "yes", "y", false, "Skip confirmation prompt")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Show what would be removed without deleting anything")
	return cmd
}

func newCleanCacheCmd() *cobra.Command {
	var configPath string
	var siteKey string
	var yes bool
	cmd := &cobra.Command{
		Use:   "cache",
		Short: "Clean cached data for a specific site or all sites",
		RunE: func(cmd *cobra.Command, args []string) error {
			console := newConsole()
			runtime, _, err := loadRuntime(console, configPath)
			if err != nil {
				return err
			}
			if runtime == nil {
				return nil
			}

			desc := "all site caches"
			if siteKey != "" {
				desc = fmt.Sprintf("site cache for %q", siteKey)
			}
			if !yes {
				confirm, err := console.Confirm("Are you sure you want to remove "+desc+"?", false)
				if err != nil {
					return err
				}
				if !confirm {
					console.Warnf("Cancelled.")
					return nil
				}
			}
			if err := runtime.CleanCache(siteKey); err != nil {
				return err
			}
			console.Successf("Successfully removed %s.", desc)
			return nil
		},
	}
	cmd.Flags().StringVar(&configPath, "config", "", "Path to the configuration file")
	cmd.Flags().StringVar(&siteKey, "site", "", "Source site key")
	cmd.Flags().BoolVarP(&yes, "yes", "y", false, "Skip confirmation prompt")
	return cmd
}

func newCleanBookCmd() *cobra.Command {
	var (
		bookStage  string
		siteKey    string
		configPath string
		startID    string
		endID      string
		noChapters bool
		metadata   bool
		media      bool
		removeAll  bool
		yes        bool
	)

	cmd := &cobra.Command{
		Use:   "book [book_ids]",
		Short: "Clean cached raw data for one or more books",
		RunE: func(cmd *cobra.Command, args []string) error {
			console := newConsole()
			runtime, _, err := loadRuntime(console, configPath)
			if err != nil {
				return err
			}
			if runtime == nil {
				return nil
			}

			if removeAll && len(args) == 0 {
				desc := "all raw data for all sites"
				if siteKey != "" {
					desc = fmt.Sprintf("all data for site %q", siteKey)
				}
				if !yes {
					confirm, err := console.Confirm("Are you sure you want to remove "+desc+"?", false)
					if err != nil {
						return err
					}
					if !confirm {
						console.Warnf("Cancelled.")
						return nil
					}
				}
				if err := runtime.CleanAllBooks(siteKey); err != nil {
					return err
				}
				console.Successf("Successfully removed %s.", desc)
				return nil
			}

			books := parseBookRefs(args, startID, endID)
			if len(books) == 0 {
				console.Warnf("No book IDs provided. Exiting.")
				return nil
			}
			if siteKey == "" {
				value, err := console.Prompt("Please enter the site key for these book(s)")
				if err != nil {
					return err
				}
				siteKey = value
			}
			if strings.TrimSpace(siteKey) == "" {
				console.Warnf("No site provided.")
				return nil
			}
			if !yes {
				confirm, err := console.Confirm("Are you sure you want to remove cached book data?", false)
				if err != nil {
					return err
				}
				if !confirm {
					console.Warnf("Cancelled.")
					return nil
				}
			}
			if err := runtime.CleanBooks(siteKey, books, bookStage, !noChapters, metadata, media, removeAll); err != nil {
				return err
			}
			for _, book := range books {
				console.Successf("Removed cached data for %s/%s", siteKey, book.BookID)
			}
			return nil
		},
	}

	cmd.Flags().StringVar(&siteKey, "site", "", "Source site key")
	cmd.Flags().StringVar(&configPath, "config", "", "Path to the configuration file")
	cmd.Flags().StringVar(&startID, "start", "", "Start chapter ID (applies only to the first book)")
	cmd.Flags().StringVar(&endID, "end", "", "End chapter ID (applies only to the first book)")
	cmd.Flags().StringVar(&bookStage, "stage", "raw", "Cleanup stage (default: raw)")
	cmd.Flags().BoolVar(&noChapters, "no-chapters", false, "Do not remove chapter data")
	cmd.Flags().BoolVar(&metadata, "metadata", false, "Remove metadata JSON")
	cmd.Flags().BoolVar(&media, "media", false, "Remove media resources")
	cmd.Flags().BoolVar(&removeAll, "all", false, "Remove all raw data for the book or site")
	cmd.Flags().BoolVarP(&yes, "yes", "y", false, "Skip confirmation prompt")
	return cmd
}
